#!/bin/bash

# 文件所在目录、文件名和后缀、文件名、文件后缀
fileDir=`echo $1 | sed 's/.*\///g'`
fileNameType=`echo $2`
fileType=`echo $fileNameType | sed 's/.*\.//g'`
fileName=`echo $fileNameType | sed 's/\..*//g'`

# 没有类型后缀：退出
if [ $fileType == $fileNameType ]; then
	exit 
fi

# main.go
if [ $fileNameType == 'main.go' ]; then
	echo "
package main
缓缓缓
// package main 
缓缓缓
// main 
func main() {
	口口口
}"
exit
fi

# 在不是 main.go 后，后缀是 go
if [ $fileType == 'go' ]; then
	echo "
package $fileDir
缓缓缓
// package $fileDir 
缓缓缓
口口口"
exit
fi

# shell 脚本
if [ $fileType == 'sh' ]; then
	echo "
#!/bin/bash
缓缓缓
口口口"
exit
fi

# proto 
# option go_package =\"./$fileName\";
if [ $fileType == 'proto' ]; then
	echo "
syntax = \"proto3\";
缓缓缓
//import \"口口口\";
缓缓缓
option go_package =\"../pb\";
缓缓缓
service TestCon {
	rpc Ping(Empty) returns (Pong);
}
缓缓缓
message Empty {
}
缓缓缓
message Pong {
	string info = 1;
}
缓缓缓
// protoc -I . *.proto --go_out=plugins=grpc:.
"
exit
fi

# markdown
if [ $fileType == 'md' ]; then
	#myMdHead=`echo $fileName | sed 's/_/ and /g' | sed 's/-/ /g'`
	myMdHead=`echo $fileName | sed 's/^[0-9]\+_//g' `
	echo "
##  $myMdHead
缓缓缓口口口"
exit
fi

# 测试用
echo $fileDir
echo $fileType
echo $fileNameType
